import './globals.css'
import { inter, roboto_mono } from './fonts';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${roboto_mono.variable}`}>{children}</body>
    </html>
  )
}
