import './globals.css'
import { usePathname } from 'next/navigation';
import { inter, roboto_mono } from './fonts';
import Navbar from '@/components/Bars/Navbar';
import Sidebar from '@/components/Bars/Sidebar';


export const metadata = {
  title: 'Exam App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${roboto_mono.variable}`}>
        {children}
      </body>
    </html>
  )
}
